server:
  name: go-sql-tutorial
  port: 8080

sql:
  driver: mysql
  data_source_name: root:123456@tcp(localhost:3306)/masterdata?charset=utf8&parseTime=True&loc=Local

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size
